/*
  In App.xaml:
  <Application.Resources>
      <vm:ViewModelLocatorTemplate xmlns:vm="clr-namespace:Code777.ViewModel"
                                   x:Key="Locator" />
  </Application.Resources>
  
  In the View:
  DataContext="{Binding Source={StaticResource Locator}, Path=ViewModelName}"
*/

using GalaSoft.MvvmLight;
using GalaSoft.MvvmLight.Ioc;
using Microsoft.Practices.ServiceLocation;
using Code777.Model;

namespace Code777.ViewModel
{
    /// <summary>
    /// Class used and autogenerated by the mvvvm light toolkit to initialzie constants
    /// </summary>
    public class ViewModelLocator
    {

        /// <summary>
        /// pages of the application
        /// </summary>
        public const string AnswerQuestionPage = @"/Pages/AnswerQuestionPage.xaml";
        public const string QuestionsPage = @"/Pages/QuestionsPage.xaml";
        public const string CardManipulationPage = @"/Pages/CardManipulation.xaml";
        public const string NotesPage = @"/Pages/Notes.xaml";
        public const string NewsItemUrl2 = @"/Pages/GamePage.xaml";
        public const string AddNotesPage = @"/Pages/NewNotePage.xaml";

        /// <summary>
        /// initialize statice locator
        /// </summary>
        static ViewModelLocator()
        {
            ServiceLocator.SetLocatorProvider(() => SimpleIoc.Default);
            SimpleIoc.Default.Register<MainViewModel>();
            SimpleIoc.Default.Register<INavigationService, NavigationService>();
            SimpleIoc.Default.Register<GameViewModel>();
        }



        /// <summary>
        /// Get the game instance
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance",
            "CA1822:MarkMembersAsStatic",
            Justification = "This non-static member is needed for data binding purposes.")]
        public GameViewModel Game
        {
            get
            {
                return ServiceLocator.Current.GetInstance<GameViewModel>();
            }
        }
        /// <summary>
        /// Gets the Main page instance.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance",
            "CA1822:MarkMembersAsStatic",
            Justification = "This non-static member is needed for data binding purposes.")]
        public MainViewModel Main
        {
            get
            {
                return ServiceLocator.Current.GetInstance<MainViewModel>();
            }
        }

        /// <summary>
        /// Cleans up all the resources.
        /// </summary>
        public static void Cleanup()
        {
        }
    }
}